name: telegram_clone
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.18.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.2
  shimmer_animation: ^2.1.0+1
  json_annotation: ^4.7.0
  intl: ^0.17.0
  provider: ^6.0.4
  email_validator: ^2.1.17
  flutter_dotenv: ^5.0.2
  http: ^0.13.5
  open_mail_app: ^0.1.0-nullsafety.3
  flutter_secure_storage: ^6.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.3.2
  json_serializable: ^6.5.4

  flutter_lints: ^2.0.0

flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/images/
    - .env
